import type { ViewStyle, TextStyle, ImageStyle } from "react-native";

type Style = ViewStyle & TextStyle & ImageStyle;

const MAP: Record<string, Style> = {
  "flex-1": { flex: 1 },
  "flex-row": { flexDirection: "row" },
  "flex-col": { flexDirection: "column" },
  "flex-wrap": { flexWrap: "wrap" },
  "flex-shrink-0": { flexShrink: 0 },
  "items-center": { alignItems: "center" },
  "items-start": { alignItems: "flex-start" },
  "items-end": { alignItems: "flex-end" },
  "justify-center": { justifyContent: "center" },
  "justify-between": { justifyContent: "space-between" },
  "justify-start": { justifyContent: "flex-start" },
  "justify-end": { justifyContent: "flex-end" },
  "self-center": { alignSelf: "center" },
  "self-start": { alignSelf: "flex-start" },
  "self-end": { alignSelf: "flex-end" },
  absolute: { position: "absolute" },
  relative: { position: "relative" },
  "inset-0": { top: 0, right: 0, bottom: 0, left: 0 },
  "overflow-hidden": { overflow: "hidden" },
  "text-center": { textAlign: "center" },
  "text-left": { textAlign: "left" },
  "text-right": { textAlign: "right" },
  "w-full": { width: "100%" },
  "h-full": { height: "100%" },
  "min-h-full": { minHeight: "100%" },
  "w-5": { width: 20 },
  "w-7": { width: 28 },
  "w-8": { width: 32 },
  "w-9": { width: 36 },
  "w-10": { width: 40 },
  "w-11": { width: 44 },
  "w-12": { width: 48 },
  "w-14": { width: 56 },
  "w-16": { width: 64 },
  "w-20": { width: 80 },
  "h-1": { height: 4 },
  "h-2": { height: 8 },
  "h-2.5": { height: 10 },
  "h-5": { height: 20 },
  "h-6": { height: 24 },
  "h-7": { height: 28 },
  "h-8": { height: 32 },
  "h-9": { height: 36 },
  "h-10": { height: 40 },
  "h-11": { height: 44 },
  "h-12": { height: 48 },
  "h-14": { height: 56 },
  "h-16": { height: 64 },
  "h-20": { height: 80 },
  "h-32": { height: 128 },
  rounded: { borderRadius: 4 },
  "rounded-md": { borderRadius: 6 },
  "rounded-lg": { borderRadius: 8 },
  "rounded-xl": { borderRadius: 12 },
  "rounded-2xl": { borderRadius: 16 },
  "rounded-3xl": { borderRadius: 24 },
  "rounded-full": { borderRadius: 9999 },
  "p-1": { padding: 4 },
  "p-2": { padding: 8 },
  "p-3": { padding: 12 },
  "p-4": { padding: 16 },
  "p-5": { padding: 20 },
  "p-6": { padding: 24 },
  "px-1": { paddingHorizontal: 4 },
  "px-1.5": { paddingHorizontal: 6 },
  "px-2": { paddingHorizontal: 8 },
  "px-2.5": { paddingHorizontal: 10 },
  "px-3": { paddingHorizontal: 12 },
  "px-3.5": { paddingHorizontal: 14 },
  "px-4": { paddingHorizontal: 16 },
  "px-5": { paddingHorizontal: 20 },
  "px-6": { paddingHorizontal: 24 },
  "px-8": { paddingHorizontal: 32 },
  "py-0.5": { paddingVertical: 2 },
  "py-1": { paddingVertical: 4 },
  "py-1.5": { paddingVertical: 6 },
  "py-2": { paddingVertical: 8 },
  "py-2.5": { paddingVertical: 10 },
  "py-3": { paddingVertical: 12 },
  "py-3.5": { paddingVertical: 14 },
  "py-4": { paddingVertical: 16 },
  "py-5": { paddingVertical: 20 },
  "py-6": { paddingVertical: 24 },
  "py-8": { paddingVertical: 32 },
  "pt-1": { paddingTop: 4 },
  "pt-2": { paddingTop: 8 },
  "pt-3": { paddingTop: 12 },
  "pt-4": { paddingTop: 16 },
  "pt-5": { paddingTop: 20 },
  "pb-1": { paddingBottom: 4 },
  "pb-2": { paddingBottom: 8 },
  "pb-4": { paddingBottom: 16 },
  "pb-5": { paddingBottom: 20 },
  "pb-6": { paddingBottom: 24 },
  "pb-8": { paddingBottom: 32 },
  "pl-0": { paddingLeft: 0 },
  "m-0": { margin: 0 },
  "mt-1": { marginTop: 4 },
  "mt-2": { marginTop: 8 },
  "mt-3": { marginTop: 12 },
  "mt-4": { marginTop: 16 },
  "mt-5": { marginTop: 20 },
  "mt-6": { marginTop: 24 },
  "mt-8": { marginTop: 32 },
  "mt-10": { marginTop: 40 },
  "mb-1": { marginBottom: 4 },
  "mb-2": { marginBottom: 8 },
  "mb-5": { marginBottom: 20 },
  "mb-6": { marginBottom: 24 },
  "ml-1": { marginLeft: 4 },
  "mr-1": { marginRight: 4 },
  "mx-4": { marginHorizontal: 16 },
  "mx-5": { marginHorizontal: 20 },
  "gap-1": { gap: 4 },
  "gap-1.5": { gap: 6 },
  "gap-2": { gap: 8 },
  "gap-3": { gap: 12 },
  "gap-4": { gap: 16 },
  "gap-5": { gap: 20 },
  "gap-12": { gap: 48 },
  "blur-sm": {},
  "select-none": {},
  "shrink-0": { flexShrink: 0 },
  "text-xs": { fontSize: 12 },
  "text-sm": { fontSize: 14 },
  "text-base": { fontSize: 16 },
  "font-bold": { fontWeight: "700" },
  "font-extrabold": { fontWeight: "800" },
  "leading-tight": { lineHeight: 20 },
  "opacity-40": { opacity: 0.4 },
  "opacity-15": { opacity: 0.15 },
};

export function tw(...classes: (string | undefined | null | false)[]): Style {
  const merged: Style = {};
  for (const cls of classes) {
    if (!cls) continue;
    for (const token of cls.split(/\s+/)) {
      const style = MAP[token];
      if (style) Object.assign(merged, style);
    }
  }
  return merged;
}
